### ISSUE TITLE
no such option: --break-system-packages

### ISSUE THREAD

**Issue by btravouillon** [buildthedocs/btd#11]
Hello,

The btd action seems broken today. Our GHA workflows are failing with:
> Usage:   
>    pip install [options] <requirement specifier> [package-index-options] ...
>    pip install [options] -r <requirements file> [package-index-options] ...
>    pip install [options] [-e] <vcs project url> ...
>    pip install [options] [-e] <local project path> ...
>    pip install [options] <archive url/path> ...
>  
>  no such option: --break-system-packages
>  Running Sphinx v6.2.1
>  
>  Configuration error:
>  There is a programmable error in your configuration file:
>  
>  Traceback (most recent call last):
>    File "/usr/local/lib/python3.9/site-packages/sphinx/config.py", line 354, in eval_config_file
>      exec(code, namespace)  # NoQA: S102
>    File "/src/docs/conf.py", line 9, in <module>
>      import sphinx_theme
>  ModuleNotFoundError: No module named 'sphinx_theme'

Example: https://github.com/mila-iqia/mila-docs/actions/runs/5533095606/jobs/10096241602

The job is using the latest container https://hub.docker.com/layers/btdi/btd/latest/images/sha256-33564ebfdb592625b7d9653526684e933b0bc56c5d45a87843e1311a2386620a?context=explore published yesterday.

**Comment by Paebbels** [comment]
I get this message too.

In addition (or caused by this) it looks like `doc/requirements.txt` isn't used to install additional packages.

Since a few days, all my documentation builds fail in many repositories.

**Comment by JimLewis** [comment]
I get this message too.

**Comment by Paebbels** [comment]
Any updates on that problem?

I have dozens of repositories awaiting documentation updates.

**Comment by btravouillon** [comment]
Hi @Paebbels ,

If this may help, here is our workaround to use btd with a previous version: https://github.com/mila-iqia/mila-docs/pull/204/files
